### PR TITLE
Debian package building And -port bugfix.

### PR DESCRIPTION
**Pull request by wdl1908**

### CODE REVIEW

**Comment by wdl1908** [comment]
Is anything being done to incorporate these fixes?

**Comment by paycoindev** [comment]
untested. hope it works.

**Comment by wdl1908** [comment]
This code has been tested by me from the moment it was commited.

**Comment by IngCr3at1on** [comment]
@wdl1908 I tested it also, I'm just trying to test the deb package stuff (I'm on arch). Looks good though.

**Comment by wdl1908** [comment]
Works perfectly on raspbian quigley tested the packages. And I'm building them crosscompiling on a jenkins installation. When the next version is out I'll provide the deb in my release page.

**Comment by IngCr3at1on** [comment]
Yeah it works great, just have to remember to update the version in the changelog so the package is named properly.

**Comment by wdl1908** [comment]
The jenkins build I use does that automatically. It uses the latest tag to make the package version.

**Pull request merged**
